### ISSUE TITLE
Add ability to toggle ore generation in the config file

### ISSUE THREAD

**Issue by MonzterAssassin** [nflantier/BigBattery#2]
As simple as this sounds, adding the ability to turn off ore generation for mods that add ores is essential when building a mod-pack, as it reduces the different ore types in the given world and eliminates duplicates taking up double the space in your chests. Please and thank you if you do decide to implement this ability in the config.

**Comment by nflantier** [comment]
i uploaded version 0.1.2 [here](https://minecraft.curseforge.com/projects/bigbattery/files) wich allow to config ores generation.

**Comment by MonzterAssassin** [comment]
Thank you for the implementation.
